spring:
  application:
    name: MCPad
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: digitalfen-mcpad
        version: 0.0.1
logging:
  pattern:
    console: